### PR TITLE
Remove duplicate name attribute from Add Tweet By URL button

### PR DESCRIPTION
**Pull request by m1es**

### CODE REVIEW

**Comment by alexkingorg** [comment]
Thanks for the fix. We use the [git flow pattern](http://nvie.com/posts/a-successful-git-branching-model/) for this repository. Can you please open the pull request against the `develop` branch? Also, please update the changelog with a note about this fix. Thank you.

**Comment by m1es** [comment]
@alexkingorg I've just changed my commit. Please let me know if it's okay this way.

**Comment by alexkingorg** [comment]
No, this pull request is still against our `master` branch, and your changes are not in version 3.0.

**Comment by m1es** [comment]
Can you tell me what version number I should use in the changelog? Thanks!

**Pull request merged**
